version: "3.8"

services:
  sherlock_api:
    build:
      context: .
      dockerfile: Dockerfile.sherlock
    container_name: sherlock_api
    ports:
      - "8001:8000"   # Maps host port 8001 to container port 8000
    env_file:
      - .env
    restart: always

  bookworm_api:
    build:
      context: .
      dockerfile: Dockerfile.bookworm
    container_name: bookworm_api
    ports:
      - "8002:8000"   # Maps host port 8002 to container port 8000
    env_file:
      - .env
    restart: always
